# Auto-generated by PIXEL DUNGEON Music Sequencer
# Paste this into a new file: music/credits_theme.gd
extends RefCounted

const SONG_DATA: Dictionary = {
	"name": "credits_theme",
	"bpm": 120,
	"beats_per_bar": 4,
	"subdivisions": 4,
	"total_bars": 4,
	"tracks": [
		{
			"name": "Lead",
			"waveform": "sawtooth",
			"volume": 0.8,
			"notes": [[72, 0, 16], [78, 16, 16], [72, 32, 16], [61, 48, 16]]
		},
		{
			"name": "Harmony",
			"waveform": "sine",
			"volume": 0.8,
			"notes": [[60, 0, 16], [66, 16, 16], [60, 32, 16], [49, 48, 16]]
		},
	],
	"tempo_changes": [[0, 120]]
}
