# Auto-generated by PIXEL DUNGEON Music Sequencer
# Death sound effect — descending chromatic run into a held low note
extends RefCounted

const SONG_DATA: Dictionary = {
	"name": "deathsoundeffect",
	"bpm": 120,
	"beats_per_bar": 4,
	"subdivisions": 4,
	"total_bars": 1,
	"tracks": [
		{
			"name": "Lead",
			"waveform": "square",
			"volume": 0.8,
			"notes": [[83, 0, 1], [82, 1, 1], [81, 2, 1], [80, 3, 1], [79, 4, 1], [78, 5, 1], [77, 6, 1], [76, 7, 19]]
		},
	],
	"tempo_changes": [[0, 120]]
}
